### ISSUE TITLE
"Error: getaddrinfo ENOTFOUND undefined" while running "npm run seed"

### ISSUE THREAD

**Issue by sharmapr25** [shahednasser/medusa-marketplace-tutorial#26]
Hi team,
I am unable to run the seed command as described in the readme.
While running command 
> npm run seed

Getting error as below:
``` 
> medusa-starter-default@0.0.1 seed /home/ec2-user/medusa-marketplace-tutorial
> medusa seed -f ./data/seed.json

Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined'
}

Note : Running this on Linux operating system.

**Comment by sharmapr25** [comment]
I got the solution for it.
First, I had two medusa running in my system. I have used globally installed medusa-cli.
```
sudo medusa seed -f ./data/seed.json
```

After it, I have received an error of 
```
Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 5432
}
```
It has indicated that the PostgreSQL server is not getting connected. 

After checking a lot, there was a difference between the env variable setup in `medusa.config.js` and the `.env` file.
In my case, the `.env` file has the `DATABASE_URL` variable, and in `medusa.config.js` it requires DB_USERNAME and other environmental variables.
 ```
database_url: postgres://${process.env.DB_USERNAME}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/${process.env.DB_SCHEME}
```
I have replaced the environment variables in `medusa.config.js`
 ```
database_url: process.env.DATABASE_URL
```
It worked out. 🤟 🎉
